resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: git-clone-resource
  type: git
  source:
    branch: master
    uri: https://github.com/drahnr/rs-ec-perf.git

- name: git-pull-request-resource
  type: pull-request
  source:
    repository: drahnr/rs-ec-perf
    access_token: ((sirmergealot-github-token))

- name: env-glibc
  type: registry-image
  source:
    repository: quay.io/drahnr/rust-glibc-builder

jobs:
####################################################################################
#                              P U L L - R E Q U E S T
####################################################################################
  - name: pr-validate
    build_logs_to_retain: 10
    public: true
    serial: true
    plan:
    - in_parallel:
      - get: git-pull-request-resource
        resource: git-pull-request-resource
        version: every
        trigger: true

      - get: env-glibc

    - in_parallel:
      - put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: meta-check
          status: pending
      - put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: compile
          status: pending
      - put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: unit-tests
          status: pending
      - put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: win64-cross-build
          status: pending

    - in_parallel:
      - task: compile-pr
        timeout: 20m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-pull-request-resource
          caches:
          - path: cargo_home
          - path: target
          run:
            # user: root
            path: sh
            args:
            - -exc
            - |
              export CARGO_HOME="$(pwd)/../cargo_home"
              export CARGO_TARGET_DIR="$(pwd)/../target"
              sudo mkdir -p ${CARGO_HOME} ${CARGO_TARGET_DIR}
              sudo chown $(whoami): -Rf ${CARGO_HOME} ${CARGO_TARGET_DIR} .
              rustc +stable --version --verbose

              export EXE="${CARGO_TARGET_DIR}/release/rs-ec-perf"

              cargo +stable build --release

            dir: git-pull-request-resource

        on_success:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: compile
            status: success
        on_failure:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: compile
            status: failure

      - task: unit-tests-pr
        timeout: 20m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-pull-request-resource
          caches:
          - path: cargo_home
          run:
            # user: root
            path: sh
            args:
            - -exc
            - |
              export CARGO_HOME="$(pwd)/../cargo_home"
              export CARGO_TARGET_DIR="$(pwd)/../target"
              sudo mkdir -p ${CARGO_HOME} ${CARGO_TARGET_DIR}
              sudo chown $(whoami): -Rf ${CARGO_HOME} ${CARGO_TARGET_DIR} .
              rustc +stable --version --verbose

              cargo +stable test --all
            dir: git-pull-request-resource
          caches:
          - path: cargo

        on_success:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: unit-tests
            status: success
        on_failure:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: unit-tests
            status: failure

      - task: pr-win64-cross-build
        timeout: 20m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-pull-request-resource
          caches:
          - path: cargo_home
          - path: target
          run:
            path: sh
            args:
            - -exc
            - |
              export CARGO_HOME="$(pwd)/../cargo_home"
              export CARGO_TARGET_DIR="$(pwd)/../target"
              sudo mkdir -p ${CARGO_HOME} ${CARGO_TARGET_DIR}
              sudo chown $(whoami): -Rf ${CARGO_HOME} ${CARGO_TARGET_DIR} .
              rustc +stable --version --verbose

              cargo build --target x86_64-pc-windows-gnu

            dir: git-pull-request-resource

        on_success:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: win64-cross-build
            status: success

        on_failure:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: win64-cross-build
            status: failure

      - try:
          task: format-check
          timeout: 5m
          image: env-glibc
          config:
            platform: linux
            inputs:
            - name: git-pull-request-resource
            caches:
            - path: cargo_home
            - path: target
            run:
              # user: root
              path: sh
              args:
              - -exc
              - |
                export CARGO_HOME="$(pwd)/../cargo_home"
                export CARGO_TARGET_DIR="$(pwd)/../target"
                sudo mkdir -p ${CARGO_HOME} ${CARGO_TARGET_DIR}
                sudo chown $(whoami): -Rf ${CARGO_HOME} ${CARGO_TARGET_DIR} .
                rustc +stable --version --verbose

                cargo +stable fmt -- --check

              dir: git-pull-request-resource

          on_success:
            put: git-pull-request-resource
            params:
              path: git-pull-request-resource
              context: meta-check
              status: success

          on_failure:
            put: git-pull-request-resource
            params:
              path: git-pull-request-resource
              context: meta-check
              status: failure

  ####################################################################################
  #                                 M A S T E R
  ####################################################################################
  - name: master-validate
    build_logs_to_retain: 10
    public: true
    serial: true
    plan:
    - in_parallel:
      - get: env-glibc
      - get: git-repo
        resource: git-clone-resource
        trigger: true

    - in_parallel:
      - task: compile-master
        timeout: 10m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-repo
          caches:
          - path: cargo_home
          - path: target
          run:
            # user: root
            path: sh
            args:
            - -exc
            - |
              export CARGO_HOME="$(pwd)/../cargo_home"
              export CARGO_TARGET_DIR="$(pwd)/../target"
              sudo mkdir -p ${CARGO_HOME} ${CARGO_TARGET_DIR}
              sudo chown $(whoami): -Rf ${CARGO_HOME} ${CARGO_TARGET_DIR} .
              rustc +stable --version --verbose

              export EXE="${CARGO_TARGET_DIR}/release/rs-ec-perf"

              cargo +stable build --release

            dir: git-repo

      - task: win64-cross-build-master
        timeout: 15m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-repo
          caches:
          - path: cargo_home
          - path: target
          run:
            path: sh
            args:
            - -exc
            - |
              export CARGO_HOME="$(pwd)/../cargo_home"
              export CARGO_TARGET_DIR="$(pwd)/../target"
              sudo mkdir -p ${CARGO_HOME} ${CARGO_TARGET_DIR}
              sudo chown $(whoami): -Rf ${CARGO_HOME} ${CARGO_TARGET_DIR} .
              rustc +stable --version --verbose

              cargo build --target x86_64-pc-windows-gnu
            dir: git-repo

      - task: unit-tests-master
        timeout: 10m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-repo
          caches:
          - path: cargo_home
          - path: target
          run:
            # user: root
            path: sh
            args:
            - -exc
            - |
              export CARGO_HOME="$(pwd)/../cargo_home"
              export CARGO_TARGET_DIR="$(pwd)/../target"
              sudo mkdir -p ${CARGO_HOME} ${CARGO_TARGET_DIR}
              sudo chown $(whoami): -Rf ${CARGO_HOME} ${CARGO_TARGET_DIR} .
              rustc +stable --version --verbose

              cargo +stable test --all
            dir: git-repo

      - try:
          task: validate-meta-master
          timeout: 5m
          image: env-glibc
          config:
            platform: linux
            inputs:
            - name: git-repo
            caches:
            - path: cargo_home
            - path: target

            run:
              # user: root
              path: sh
              args:
              - -exc
              - |
                export CARGO_HOME="$(pwd)/../cargo_home"
                export CARGO_TARGET_DIR="$(pwd)/../target"
                sudo mkdir -p ${CARGO_HOME} ${CARGO_TARGET_DIR}
                sudo chown $(whoami): -Rf ${CARGO_HOME} ${CARGO_TARGET_DIR} .
                rustc +stable --version --verbose

                cargo +stable fmt -- --check

              dir: git-repo
